config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about" => "pages#about"
  get "objective" => "pages#objective"
  get "team" => "pages#team"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def objective
  end
  
  def team
  end
  
  def about
  end
  	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "G's Crowdbuilding Apps", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">         
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Objective", objective_path %></li>
        <li><%= link_to "Team", team_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron center">
	<h1>About us</h1>
	<p>We are a group of everyday people working hard to bring new, useful and 
	exciting apps to the palms of your hands, click here to <%=link_to "Keep in contact with whats happening", "#", class: "btn btn-primary btn-lg" %></p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to Crowdsourced App builders!</h1>

	<p>
		Click here to <%= link_to "Login", "#", class: "btn btn-primary btn-lg" %>
		Or here to <%= link_to "Sign Up and Get Involved", "#", class: "btn btn-primary btn-lg" %>
	</p>
</div>

app/views/pages/objective.html.erb
<div class="jumbotron center">
	<h1>Our Objective</h1>
	<p>The initial objective and "Stage One" of our app, is to simply collect from anyone who is interested, a list of the main functions which the app needs to have, if your feature is built into the app, you will receive access to it free of charge, for Life!, click here to <%=link_to "Submit the features you would like to see included", "#", class: "btn btn-primary btn-lg" %></p>
</div>

app/views/pages/team.html.erb
<div class="jumbotron center">
	<h1>Our Team</h1>
	<p>Our Team is growing all the time, its open to anyone who would like to become involved. If you would like to be part of the team, simply click here to add your details and <%=link_to "Become part of the Team...", "#", class: "btn btn-primary btn-lg" %></p>
</div>